// write a java script program to get all different information from the user , and then display in the console =>
document.getElementById("mainHeading").innerHTML = "display all information from the user in the console"
var fristUserName = window.prompt("please enter the frist name of the user is : ")
console.log("the frist name of the user is : ",fristUserName)
var secondUserName = window.prompt("please enter the second name of the user is : ")
console.log("the second name of the user is : ",secondUserName)
var lastUserName = window.prompt("please enter the last name of the user is : ")
console.log("the last name of the user is : ",lastUserName)
console.log("the full name of the user is : ",fristUserName," ",secondUserName," ",lastUserName)
var userAge = window.prompt("please enter the age of the user is : ") 
console.log("the age of the user is = ",userAge," years")
var userGender = window.prompt("please enter the gender of the user is : ")
console.log("the gender of the user is : ",userGender)
var userAddress = window.prompt("please enter the address of the user is : ")
console.log("the address of the user is : ",userAddress)
var userUniversity = window.prompt("please enter the university of the user is : ")
console.log("the university of the user is : ",userUniversity)
var userFaculty = window.prompt("please enter the faulty of the user is : ")
console.log("the faculty of the user is : ",userFaculty)